### ISSUE TITLE
can't see my italian CRS/CNS in 10.10 keychain

### ISSUE THREAD

**Issue by ale275** [OpenSC/OpenSC.tokend#14]
Hallo, I've built and installed latest version of OpenSC (0.15.0). MY SC works flawless with firefox using the pkcs11 library, but it doesn't show up in OS X keychain. Is there any way to fix this?

**Comment by frankmorgner** [comment]
@puccia @sschutte @wtmann @resoli are you experiencing the same problem?

**Comment by resoli** [comment]
Sorry, I can't test on MacOS, nor hava any experience with OpenSC on it .

**Comment by ale275** [comment]
With latest versino no problem on El Capitan. Will check on 10.10

Alessandro Gritti

**Comment by sschutte** [comment]
I would need to update my OSX installation, then I can take a look.

**Comment by wtmann** [comment]
I don't have a Mac so I can't test it. Sorry.

**Comment by frankmorgner** [comment]
closing with https://github.com/OpenSC/OpenSC.tokend/issues/14#issuecomment-159526116
