### ISSUE TITLE
Mac OS X Yosemite Problem

### ISSUE THREAD

**Issue by varMari** [OpenSC/OpenSC.tokend#17]
I built OpenSC for Mac and installed it on Mavericks and Yosemite. After the installation Opensc.tokend is added in /Library/Security/tokend directory. On Mavericks it works fine, in Chrome, Firefox, Safari and I can use its tools from terminal too. As for the Yosemite it works in Firefox and I can use its tools from terminal, but I couldn't make it work in Chrome and Safari. My smart card is not added in Keychain. Can you tell me what the problem is? Is there any solution?

**Comment by varMari** [comment]
These are the system log screenshots.

![opensclog](https://cloud.githubusercontent.com/assets/13207687/9325005/5272099c-45a0-11e5-952c-316c4166b892.png)
![keychain1](https://cloud.githubusercontent.com/assets/13207687/9325004/526dfef6-45a0-11e5-8c9e-15eaa4f1297f.png)
![keychain2](https://cloud.githubusercontent.com/assets/13207687/9325006/5273bde6-45a0-11e5-8793-df933cb112d2.png)

**Comment by martinpaljak** [comment]
What is your smart card? Can you enable OpenSC logging? A crashing tokend is a hard thing to fix.

**Comment by varMari** [comment]
@martinpaljak . My smart card is Georgian eID card. I enabled OpenSC logging but it logs only if i use OpenSC from terminal and it has no errors.

**Comment by varMari** [comment]
@martinpaljak  I enabled logging but it logs only if i use OpenSC from terminal and it has no errors

**Comment by martinpaljak** [comment]
You built the Tokend by hand ? As you have a debug target? Please try with this: https://github.com/OpenSC/OpenSC/releases/tag/0.15.0

**Comment by varMari** [comment]
No. I didn't build it by hand. I've already tried that. Does Tokend work on Yosemite at all? @martinpaljak

**Comment by mouse07410** [comment]
For me neither OpenSC.tokend nor any other OpenSC opponent seems to work on Yosemite, at least with Yubikey NEO (with PIV applet fully provisioned).

OpenSC.tokend refuses to recognize CAC. Other OpenSC utilities at least admit to seeing it when inserted.

Sent from my iPad

On Aug 24, 2015, at 02:55, varMari <notifications@github.com<mailto:notifications@github.com>> wrote:


No. I didn't build it by hand. I've already tried that. Does Tokend work on Yosemite at all? @martinpaljak<https://github.com/martinpaljak>

**Comment by mouse07410** [comment]
Use OpenSC.tokend fork by @frankmorgner or myself. Those do work.

**Comment by frankmorgner** [comment]
that's merged now!
