### ISSUE TITLE
OpenSC always prompts for a PIN to access public key, which is wrong

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC.tokend#24]
OpenSC (involved files are `src/pkcs11/framework-pkcs15.c` and `src/tools/pkcs15-tool.c`) always prompts for a PIN to access public keys, which is not correct. The following patch fixes this problem. It has been tested on El Capitan 10.11.2, and worked fine with my PIV tokens. My patch also adds some debugging output to `src/libopensc/pkcs15-sec.c` - I needed that to debug signatures based on SHA-2, and ECDSA. It has no relation to this issue, or this fix - so feel free to incorporate it if it seems useful, or ignore otherwise. *I understand the PR mechanism, but it doesn't seem worth it cloning the entire OpenSC repo merely to submit 5-6 lines of change.*

```
diff --git a/src/libopensc/pkcs15-sec.c b/src/libopensc/pkcs15-sec.c
index 019d8a1..fdd32de 100644
--- a/src/libopensc/pkcs15-sec.c
+++ b/src/libopensc/pkcs15-sec.c
@@ -336,8 +336,11 @@ int sc_pkcs15_compute_signature(struct sc_pkcs15_card *p15card,
        }

        /* Probably never happens, but better make sure */
-       if (inlen > sizeof(buf) || outlen < modlen)
+       if (inlen > sizeof(buf) || outlen < modlen) {
+               sc_log(ctx, "inlen=%d sizeof(buf)=%d outlen=%d modlen=%d",
+                      inlen, sizeof(buf), outlen, modlen);
                LOG_FUNC_RETURN(ctx, SC_ERROR_BUFFER_TOO_SMALL);
+       }

        memcpy(buf, in, inlen);

diff --git a/src/pkcs11/framework-pkcs15.c b/src/pkcs11/framework-pkcs15.c
index e103550..89e811d 100644
--- a/src/pkcs11/framework-pkcs15.c
+++ b/src/pkcs11/framework-pkcs15.c
@@ -3880,8 +3880,13 @@ pkcs15_pubkey_get_attribute(struct sc_pkcs11_session *session, void *object, CK_
        case CKA_TOKEN:
        case CKA_SENSITIVE:
                check_attribute_buffer(attr, sizeof(CK_BBOOL));
-               *(CK_BBOOL*)attr->pValue = TRUE;
-               break;
+               if (pubkey->pub_p15obj)
+                       *(CK_BBOOL*)attr->pValue = (pubkey->pub_p15obj->flags & SC_PKCS15_PIN_FLAG_CASE_SENSITIVE) != 0;
+               else if (cert && cert->cert_p15obj)
+                       *(CK_BBOOL*)attr->pValue = (cert->pub_p15obj->flags & SC_PKCS15_PIN_FLAG_CASE_SENSITIVE) != 0;
+               else
+                       return CKR_ATTRIBUTE_TYPE_INVALID;
+                       break;
        case CKA_LOCAL:
                check_attribute_buffer(attr, sizeof(CK_BBOOL));
                if (pubkey->pub_info)
diff --git a/src/tools/pkcs15-tool.c b/src/tools/pkcs15-tool.c
index 7aa981f..1d4a59a 100644
--- a/src/tools/pkcs15-tool.c
+++ b/src/tools/pkcs15-tool.c
@@ -688,8 +688,10 @@ static int read_public_key(void)
        if (r >= 0) {
                if (verbose)
                        printf("Reading public key with ID '%s'\n", opt_pubkey);
+#if 0
                r = authenticate(obj);
                if (r >= 0)
+#endif
                        r = sc_pkcs15_read_pubkey(p15card, obj, &pubkey);
        } else if (r == SC_ERROR_OBJECT_NOT_FOUND) {
                /* No pubkey - try if there's a certificate */
```

**Comment by frankmorgner** [comment]
The PR mechanism is entirely designed around this feature :wink:, please use it! PRs are best for quick integration and quick feedback/comments.

Also, I see two changes here:

1. *Support for correctly propagating case sensitivity.* Please the correct types here (`TRUE` and `FALSE`)
2. *Remove authentication for reading the pubkeys.* This looks correct. However, please remove those lines completely and indent the following line correctly.

**Comment by mouse07410** [comment]
Ok. I will clone OpenSC (though maintaining this clone us the last thing I need). 

Regarding (1), it's the *exact* copy of the existing code a hundred of so lines down In the same file. Why is assignment to logical expression is good enough there but not here? And if it's bad, why not refactor that part? I thought you wanted the code to look uniform?

Regarding (2) - will do.
