### ISSUE TITLE
With Mac OS X 10.11.5 tokend does not work any more

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/OpenSC.tokend#27]
Everything was fine until the upgrade to Mac OS X 10.11.5. From that point, no token is recognized by tokend. Low-level tools and OpenSSL access seem to work OK.

Mac OS X 10.11.5, Xcode-7.3.1. OpenSC from Github *towards-0.16.0*. https://github.com/mouse07410/OpenSC.tokend.git, which has been working fine until now. Thursby PKard tokend also stopped recognizing tokens.

Here's what I find in `system.log`:
```
May 19 23:45:05 Uris-MacBook-Air com.apple.SecurityServer[98]: Token reader Yubico Yubikey NEO OTP+U2F+CCID inserted into system
May 19 23:45:05 Uris-MacBook-Air com.apple.SecurityServer[98]: reader Yubico Yubikey NEO OTP+U2F+CCID: state changed 0 -> 34
May 19 23:45:06 Uris-MacBook-Air com.apple.SecurityServer[98]: token in reader Yubico Yubikey NEO OTP+U2F+CCID cannot be used (error 100002)
```

`/tmp/opensc-debug.log` is attached (at `debug=9`):
[opensc-debug-0.16.0-a.txt](https://github.com/OpenSC/OpenSC.tokend/files/273851/opensc-debug-0.16.0-a.txt)

OpenSC-level access and OpenSSL/libp11 still are OK - see the attached. It starts with the token being inserted, and then I run my OpenSSL-based test (which succeeds).
[opensc-debug-0.16.0-b.txt](https://github.com/OpenSC/OpenSC.tokend/files/273852/opensc-debug-0.16.0-b.txt)

Also, neither one of the tokend's (OpenSC.tokend and Thursby PKard) managed to store anything in `/var/db/TokenCache` directory. Before they'd store the token info there... *Before you ask - no, I did not try them both at the same time. One was uninstalled before installing the other one.*

**UPDATE**

The problem was alleviated by adding symlink as suggested by Metsma here: https://forums.developer.apple.com/message/139013#139013

**Comment by frankmorgner** [comment]
Following https://forums.developer.apple.com/message/139013#139013, this is a problem with OS X CCID driver rather than with OpenSC, correct?

**Comment by LudovicRousseau** [comment]
@mouse07410 please run the following command on your Mac and post the result:
```
ls -lR /usr/libexec/SmartCardServices/drivers
```

See also http://ludovicrousseau.blogspot.fr/2016/04/os-x-el-capitan-and-ccid-driver-upgrades.html

**Comment by martinpaljak** [comment]
Instead of the half-solution workaround, you can take the latest driver version (and get Info.plist that contains all latest readers and which can be extended by hand as well)

https://github.com/martinpaljak/osx-ccid-installer

**Comment by mouse07410** [comment]
> this is a problem with OS X CCID driver rather than with OpenSC, correct?

Yes, this is my understanding.

> please run the following command on your Mac and post the result

@LudovicRousseau here it is:
```
$ ls -lR /usr/libexec/SmartCardServices/drivers
total 0
drwxr-xr-x  3 root  wheel  102 Sep 23  2015 ifd-ccid.bundle

/usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle:
total 0
drwxr-xr-x  5 root  wheel  170 Apr 20 10:27 Contents

/usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle/Contents:
total 24
-rw-r--r--  1 root  wheel  36860 Dec 21 00:05 Info.plist
drwxr-xr-x  5 root  wheel    170 Apr 20 10:27 MacOS
-rw-r--r--  1 root  wheel    470 Dec 21 00:05 version.plist

/usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle/Contents/MacOS:
total 344
lrwxr-xr-x  1 root  wheel      20 Apr 19 13:20 libccid.dylib -> libccid.dylib.1.4.20
-rwxr-xr-x  1 root  wheel  166096 Jan 13 21:03 libccid.dylib.1.4.20
-rwxr-xr-x  1 root  wheel  166096 Mar 12 03:30 libccid.dylib.1.4.21
```

> Instead of the half-solution workaround, you can take the latest driver version (and get Info.plist that contains all latest readers and which can be extended by hand, without fiddling with SIP)

@martinpaljak thank you, building/installing the latest driver as we speak. One question: the process created *two* packages: `ccid-installed.pkg` and `ifd-ccid.pkg`. Do I need to install both? Also, got a problem - reported to the relevant Github project https://github.com/martinpaljak/osx-ccid-installer/issues/6

**Comment by LudovicRousseau** [comment]
@mouse07410 your driver installation does not seam to be broken.
Please read http://ludovicrousseau.blogspot.fr/2014/03/level-1-smart-card-support-on-mac-os-x.html

**Comment by mouse07410** [comment]
@LudovicRousseau thank you! That's good to know. But I would still benefit from installing the newer version that @martinpaljak pointed me at, right?  

And it's a little strange that the symlink points at an older version...

**Comment by martinpaljak** [comment]
Apparently OSX is a bit messy with this thing.

The OSX installer has been updated to include ccid-1.4.24

https://github.com/martinpaljak/osx-ccid-installer/releases

**Comment by mouse07410** [comment]
Thank you! Actually, the build (of ccid-installer) works smoothly - so I just rebuilt from the sources. I would still like to learn why there are *two* packages built, and whether one has to install both of them. Unfortunately, the README seems silent on this topic.
